name: airline_passengers
channels:
  - conda-forge
dependencies:
  - bqplot=0.12.33
  - jupyterlab=3.4.4
  - seaborn=0.11.2
  - scipy=1.9.0
  - ipywidgets=7.7.1
  - pandas=1.4.3
  - python=3.10.5
  - numpy=1.23.1
  - matplotlib
  - scikit-learn
